In [107]:
import numpy as np

r = np.random.rand(100,2)

In [88]:
fjarlaegdir = np.hypot(*(r - r[0,:]).T)

In [117]:
np.argwhere(fjarlaegdir[:]*10 < 1)

array([[ 0],
       [32]])

In [109]:
ad_faerast = fjarlaegdir[:] < 0.1
r[ad_faerast, 1]  = r[ad_faerast,1]* 1000
r


array([[6.93351093e-01, 1.62819387e+04],
       [5.39102063e-01, 6.35074983e-01],
       [4.20206625e-01, 6.00648624e-01],
       [8.59869643e-01, 6.38316368e-01],
       [5.23603281e-01, 4.68293756e-01],
       [3.86978338e-01, 7.76141475e-01],
       [1.06215051e-01, 1.01793409e-01],
       [6.70392042e-02, 8.84912432e-01],
       [1.43600519e-01, 9.37383144e-01],
       [2.40212359e-01, 9.03480090e-01],
       [8.34614301e-01, 1.08655905e-01],
       [8.46996398e-01, 6.80788390e-01],
       [8.02104805e-01, 4.08088664e-02],
       [9.90157627e-01, 9.04812994e-01],
       [8.90693989e-02, 8.03454128e-01],
       [1.50183582e-01, 5.94223102e-01],
       [8.71605980e-01, 6.91815766e-03],
       [8.48058201e-01, 5.85684562e-01],
       [3.84839520e-01, 2.43195706e-01],
       [2.23619939e-01, 1.53436247e-01],
       [3.47862821e-01, 1.11939695e-01],
       [1.85898050e-01, 3.67026256e-01],
       [1.91882354e-01, 4.10395112e-01],
       [6.02801415e-01, 8.64650022e-01],
       [2.935591

In [112]:
arr = np.array((1,2,3,4,5,6,7,8,9,19))
arr2 = np.zeros(10)
filter = arr[:] < 5
arr2[filter] = 100
arr2

array([100., 100., 100., 100.,   0.,   0.,   0.,   0.,   0.,   0.])

In [115]:
q = []
for i in r:
    q += i
    
len(r)

100